"""Upstream-generated vector replay, separate from transaction checks.

The pinned generator has no B32 display-name branch and prints 'L' when built
with B32. We preserve its bytes and record the actual compile parameters.
These are vectors generated by upstream code, not an independent implementation.
"""
from hashlib import sha256
from pathlib import Path
import argparse
import json
import re
import subprocess
import tempfile
import time

from .crypto import ROOT
from .shrincs_build import KAT, SHRINCS_COMMIT, UPSTREAM
from .shrincs_demo import native_tool


def parse_vectors(text):
    records = []
    for block in re.findall(r'^count\s*=.*?^result\s*=\s*(?:Pass|Fail)\s*$', text, re.M | re.S):
        records.append({key.strip():value.strip() for key, value in
                        (line.split('=', 1) for line in block.splitlines() if '=' in line)})
    return records


def generate(path, full=False):
    """Collect one message group, or let the complete 375-vector pass run finish."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='btc-pq-shrincs-kat-') as directory:
        directory = Path(directory)
        with (directory/'generator.log').open('w') as log:
            process = subprocess.Popen([str(KAT)], cwd=directory, stdout=log, stderr=log)
            start = time.monotonic()
            try:
                if full:
                    if process.wait() != 0:
                        raise RuntimeError('full upstream generator failed')
                    output = directory/'SHRINCS-L_pass.rsp'
                    text = output.read_text()
                    if len(parse_vectors(text)) != 375:
                        raise RuntimeError('full upstream generator did not complete 375 vectors')
                    path.write_text(text)
                    return
                while True:
                    output = directory/'SHRINCS-L_pass.rsp'
                    text = output.read_text() if output.exists() else ''
                    ends = list(re.finditer(r'^result = (Pass|Fail)\n', text, re.M))
                    if len(ends) >= 15:
                        path.write_text(text[:ends[14].end()]+'\n')
                        break
                    if process.poll() is not None:
                        raise RuntimeError('upstream generator exited before 15 complete records')
                    if time.monotonic()-start > 600:
                        raise TimeoutError('upstream vector generation exceeded 10 minutes')
                    time.sleep(.25)
            finally:
                if process.poll() is None:
                    process.terminate()
                    process.wait(timeout=10)


def replay(path, expected_count=15):
    path = Path(path)
    records = parse_vectors(path.read_text())
    if len(records) != expected_count or [int(r['count']) for r in records] != list(range(expected_count)):
        raise ValueError('upstream vector count or sequence mismatch')
    cases = []
    with tempfile.TemporaryDirectory() as directory:
        directory = Path(directory)
        pk, msg, sig, seed = [directory/name for name in ('pk.hex', 'msg.hex', 'sig.hex', 'seed.hex')]
        for record in records:
            if record['result'] != 'Pass' or len(bytes.fromhex(record['sig'])) != int(record['siglen']):
                raise ValueError('invalid upstream expected answer')
            for p, value in ((pk, record['pk']), (msg, record['msg']), (sig, record['sig']), (seed, record['seed'])):
                p.write_text(value+'\n')
            public_key_matches = native_tool('pubkey', seed)['public_key'] == record['pk']
            valid = native_tool('verify', pk, msg, sig)['valid']
            message = bytes.fromhex(record['msg'])
            msg.write_text((bytes([message[0]^1])+message[1:]).hex()+'\n')
            changed_message_valid = native_tool('verify', pk, msg, sig)['valid']
            if not public_key_matches or not valid or changed_message_valid:
                raise AssertionError('upstream vector '+record['count'])
            cases.append(dict(count=int(record['count']), signature_bytes=int(record['siglen']),
                              public_key_matches=True, valid=True, changed_message_valid=False))
    result = dict(shrincs_commit=SHRINCS_COMMIT, actual_parameters='SHRINCS_B32',
                  generator_display_name='L (upstream has no B32 label branch)',
                  scope=('complete unmodified upstream pass generator' if expected_count == 375 else
                         'first message group from unmodified upstream generator, not full upstream suite'),
                  full_pass_generator=expected_count == 375,
                  independent_implementation=False, vectors_sha256=sha256(path.read_bytes()).hexdigest(),
                  generator_sha256=sha256((UPSTREAM/'kat/kat_gen_pass.cpp').read_bytes()).hexdigest(),
                  cases=cases, all_expectations_met=True)
    path.with_name(path.stem+'-report.json').write_text(json.dumps(result, indent=2)+'\n')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generate', action='store_true')
    parser.add_argument('--full', action='store_true', help='complete 375-vector pass generator; generation takes several minutes')
    parser.add_argument('--path', type=Path)
    args = parser.parse_args()
    path = args.path or ROOT/('results/shrincs-demo/upstream-kat-full.rsp' if args.full else
                             'results/shrincs-demo/upstream-kat.rsp')
    if args.generate:
        generate(path, args.full)
    result = replay(path, 375 if args.full else 15)
    print(f"SHRINCS_B32: {len(result['cases'])} upstream vectors and changed-message controls passed")


if __name__ == '__main__':
    main()
